### ISSUE TITLE
Panic on ESP32S3 with embassy 

### ISSUE THREAD

**Issue by VersBinarii** [avsaase/weact-studio-epd#8] opened 2024-07-22 21:30 UTC
Hello,
I'm testing this driver on a esp32s3 board using the Tricolor v4 eink2in13 display.
The following code:
```rust
    let io = Io::new(peripherals.GPIO, peripherals.IO_MUX);
    let sclk = io.pins.gpio1;
    let din = io.pins.gpio2;
    let eink_cs = Output::new(io.pins.gpio3, Level::High);
    let eink_dc = Output::new(io.pins.gpio4, Level::High);
    let busy = Input::new(io.pins.gpio7, Pull::Up);
    let reset = Output::new(io.pins.gpio8, Level::High);
    let sda = io.pins.gpio5;
    let scl = io.pins.gpio6;
    let dma = Dma::new(peripherals.DMA);
    let dma_channel = dma.channel0;
    let (mut tx_descriptors, mut rx_descriptors) = dma_descriptors!(32000);

    let spi = Spi::new(peripherals.SPI2, 100.kHz(), SpiMode::Mode0, &clocks)
        .with_mosi(din)
        .with_sck(sclk)
        .with_dma(dma_channel.configure_for_async(
            false,
            &mut tx_descriptors,
            &mut rx_descriptors,
            DmaPriority::Priority0,
        ));
    let spi_device = ExclusiveDevice::new(spi, eink_cs, Delay).unwrap();
    let spi_interface = SpiInterface::new(spi_device, eink_dc);
    let mut driver = WeActStudio213TriColorDriver::new(spi_interface, busy, reset, Delay);
    let mut display = Display213TriColor::new();
    display.set_rotation(DisplayRotation::Rotate90);
    driver.init().await.expect("Failed to init");
    let style = MonoTextStyle::new(&PROFONT_24_POINT, TriColor::Red);
    let mut string_buf = String::<30>::new();
    write!(string_buf, "Time:\nInterval:").unwrap();
    let _ = Text::with_text_style(&string_buf, Point::new(8, 40), style, TextStyle::default())
        .draw(&mut display)
        .unwrap();
    string_buf.clear();
    driver
        .full_update(display)
        .await
        .expect("Failed to fully update display");
```
causes the following panic:
```
I (45) boot: ESP-IDF v5.1-beta1-378-gea5e0ff298-dirt 2nd stage bootloader
I (46) boot: compile time Jun  7 2023 08:07:32
I (47) boot: Multicore bootloader
I (51) boot: chip revision: v0.2
I (55) boot.esp32s3: Boot SPI Speed : 40MHz
I (59) boot.esp32s3: SPI Mode       : DIO
I (64) boot.esp32s3: SPI Flash Size : 4MB
I (69) boot: Enabling RNG early entropy source...
I (74) boot: Partition Table:
I (78) boot: ## Label            Usage          Type ST Offset   Length
I (85) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (93) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (100) boot:  2 factory          factory app      00 00 00010000 003f0000
I (108) boot: End of partition table
I (112) esp_image: segment 0: paddr=00010020 vaddr=3c010020 size=0663ch ( 26172) map
I (127) esp_image: segment 1: paddr=00016664 vaddr=3fc892b4 size=00004h (     4) load
I (129) esp_image: segment 2: paddr=00016670 vaddr=40378000 size=012b4h (  4788) load
I (139) esp_image: segment 3: paddr=0001792c vaddr=00000000 size=086ech ( 34540)
I (154) esp_image: segment 4: paddr=00020020 vaddr=42000020 size=09800h ( 38912) map
I (165) boot: Loaded app from partition at offset 0x10000
I (165) boot: Disabling RNG early entropy source...



Exception occured 'LoadProhibited'
Context
PC=0x420060b3       PS=0x00060015
0x420060b3 - core::task::wake::Waker::wake_by_ref
    at .rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/task/wake.rs:492
0x00060015 - PS_WOE
    at ??:??
A0=0x82008a80       A1=0x3fcd4450       A2=0x3fcd92c4       A3=0xffffffff       A4=0x3fc892b4
0x82008a80 - _rtc_fast_bss_start
    at ??:??
0x3fcd4450 - _ZN16embassy_executor7_export5ARENA17h2d84e85f0ae391c4E
    at ??:??
0x3fcd92c4 - _ZN130_$LT$esp_hal..dma..gdma..ChannelTxImpl$LT$_$GT$$u20$as$u20$esp_hal..dma..TxChannel$LT$esp_hal..dma..gdma..Channel$LT$_$GT$$GT$$GT$5waker5WAKER17ha5e57b74bc507d20E
    at ??:??
0xffffffff - _rtc_fast_bss_start
    at ??:??
0x3fc892b4 - _rwdata_reserved_start
    at ??:??
A5=0x00000100       A6=0x00060003       A7=0xffffffff       A8=0x00000000       A9=0x00000001
0x00000100 - XT_STK_FRMSZ
    at ??:??
0x00060003 - PS_WOE
    at ??:??
0xffffffff - _rtc_fast_bss_start
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000001 - XT_STK_PC
    at ??:??
A10=0x3fc892c0      A11=0x00000000      A12=0x3fcdc630      A13=0x3fcd4830      A14=0x3fc892c0
0x3fc892c0 - _ZN16embassy_executor7_export5ARENA17h2d84e85f0ae391c4E
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x3fcdc630 - __stack_chk_guard
    at ??:??
0x3fcd4830 - _ZN16embassy_executor7_export5ARENA17h2d84e85f0ae391c4E
    at ??:??
0x3fc892c0 - _ZN16embassy_executor7_export5ARENA17h2d84e85f0ae391c4E
    at ??:??
A15=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
SAR=00000018
EXCCAUSE=0x0000001c EXCVADDR=0x00000007
0x0000001c - XT_STK_A5
    at ??:??
0x00000007 - XT_STK_PS
    at ??:??
LBEG=0x40056f5c     LEND=0x40056f72     LCOUNT=0x00000000
0x40056f5c - rom_i2c_writeReg_Mask
    at ??:??
0x40056f72 - rom_i2c_writeReg_Mask
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
THREADPTR=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
SCOMPARE1=0x00000100
0x00000100 - XT_STK_FRMSZ
    at ??:??
BR=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
ACCLO=0x00000000    ACCHI=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
M0=0x00000000       M1=0x00000000       M2=0x00000000       M3=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
F64R_LO=0x00000000  F64R_HI=0x00000000  F64S=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
FCR=0x00000000      FSR=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
F0=0x00000000       F1=0x00000000       F2=0x00000000       F3=0x00000000       F4=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
F5=0x00000000       F6=0x00000000       F7=0x00000000       F8=0x00000000       F9=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
F10=0x00000000      F11=0x00000000      F12=0x00000000      F13=0x00000000      F14=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
0x00000000 - XT_STK_PC
    at ??:??
F15=0x00000000
0x00000000 - XT_STK_PC
    at ??:??
0x40378a7c
0x40378a7c - esp_hal::interrupt::xtensa::vectored::handle_interrupt
    at .config/cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.18.0/src/interrupt/xtensa.rs:508
0x40378a4e
0x40378a4e - esp_hal::interrupt::xtensa::vectored::handle_interrupts
    at .config/cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.18.0/src/interrupt/xtensa.rs:488
0x40378669
0x40378669 - __level_1_interrupt
    at .config/cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.18.0/src/interrupt/xtensa.rs:424
0x40378e4e
0x40378e4e - __default_naked_level_3_interrupt
    at .config/cargo/registry/src/index.crates.io-6f17d22bba15001f/xtensa-lx-rt-0.16.0/src/exception/assembly_esp32.rs:610
0x40040003
0x40040003 - rom_i2c_writeReg_Mask
    at ??:??
0x42003792
0x42003792 - esp_hal::spi::master::dma::asynch::<impl embedded_hal_async::spi::SpiBus for esp_hal::spi::master::dma::SpiDma<T,C,M,esp_hal::Async>>::write::{{closure}}
    at .config/cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.18.0/src/spi/master.rs:1423
0x42001d56
0x42001d56 - display_interface_spi::asynch::<impl display_interface::AsyncWriteOnlyDataCommand for display_interface_spi::SpiInterface<SPI,DC>>::send_commands::{{closure}}
    at .config/cargo/git/checkouts/display-interface-e507c909ebafea83/8fca041/spi/src/asynch.rs:129
0x42000efe
0x42000efe - embassy_executor::raw::util::SyncUnsafeCell<T>::get
    at .config/cargo/git/checkouts/embassy-9312dcb0ed774b29/f91244b/embassy-executor/src/raw/util.rs:55
0x4200456e
0x4200456e - main
    at ??:??
0x42009555
0x42009555 - Reset
    at ??:??
```

Removing:
```
  driver
        .full_update(display)
        .await
        .expect("Failed to fully update display");
```
stops the panic from happening and allows rest of the program to run. Would you have some pointers with how to troubleshoot this further or perhaps its more issue for embassy team? I'm uncertain if the way i initialize the SPI is the correct way since i have very little experience with ESP32 but this is the only way i was able to get it to build.

**Comment by avsaase** [comment] 2024-07-22 22:49
I don't have the right ESP32 to recreate the problem using your code but it's not unlikely that the driver retrund an error. I haven't had a chance to test the tri-color displays yet so there could definitely be a bug.

Can you remove the `expect` and print the result?

**Comment by VersBinarii** [comment] 2024-07-23 05:51
I've replaced the expect with following:
```
    if let Err(e) = driver.full_update(display).await {
        log::error!("Error: {:?}", e);
    }
```
but the panic still happens as it seems to be caused somewhere either in the esp-hal or embassy-executor.

To be honest i dont think this library is at fault. I'll try to look for the help with the embassy crowd

**Comment by avsaase** [comment] 2024-07-24 18:09
Did you manage to find the cause of the panic? I had another look through the library code and didn't a point where it would panic with the code that you shared.

**Comment by VersBinarii** [comment] 2024-07-25 07:08
I didn't find a cause of this issue yet but its definitely something between esp-hal and embassy.
Feel free to close this ticket if you wish

**Comment by avsaase** [comment] 2024-07-27 21:11
I'll close this for now but feel free to re-open if you find the issue is with this library. Good luck solving your problem. IME the Embassy people are very helpful on their matrix chat.

**Closed by avsaase** 2024-07-27 21:11 UTC

**Comment by VersBinarii** [comment] 2024-07-28 10:27
Hello
Just FYI i managed to get it working by enabling following features:
```
embassy-executor = { version = "0.5.0", features = ["nightly"] }
embassy-time = { version = "0.3.1", features = ["generic-queue"] }
```

The full working commits are following:
```
esp-hal-embassy = { version = "0.2", features = ["esp32s3"] }
embassy-executor = { version = "0.5.0", features = ["nightly"] }
embassy-time = { version = "0.3.1", features = ["generic-queue"] }
embassy-sync = { version = "0.6.0" }
embassy-embedded-hal = { version = "0.1.0" }
esp-backtrace = { version = "0.13.0", features = [
  "esp32s3",
  "exception-handler",
  "panic-handler",
  "println",
] }
esp-hal = { version = "0.19.0", features = ["esp32s3", "async"] }
esp-println = { version = "0.10.0", features = ["esp32s3", "log"] }
log = { version = "0.4.21" }
static_cell = { version = "2", features = ["nightly"] }
bme280 = { version = "0.5.1", features = ["async"] }
embedded-hal-async = { version = "1.0.0" }
display-interface = { version = "0.5" }
display-interface-spi = { version = "0.5" }
embedded-hal-bus = { version = "0.2.0", features = ["async"] }
weact-studio-epd = { git = "https://github.com/avsaase/weact-studio-epd" }
profont = { version = "0.7.0" }
embedded-graphics = { version = "0.8.1" }
heapless = { version = "0.8" }

[patch.crates-io]
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "2537fc6f4fcbdaa0fcea45a37382d61f59cc5767" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "2537fc6f4fcbdaa0fcea45a37382d61f59cc5767" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "2537fc6f4fcbdaa0fcea45a37382d61f59cc5767" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "2537fc6f4fcbdaa0fcea45a37382d61f59cc5767" }
embassy-time-queue-driver = { git = "https://github.com/embassy-rs/embassy", rev = "2537fc6f4fcbdaa0fcea45a37382d61f59cc5767" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "2537fc6f4fcbdaa0fcea45a37382d61f59cc5767" }
display-interface = { git = "https://github.com/therealprof/display-interface", rev = "8fca041b0288740678f16c1d05cce21bd3867ee5" }
display-interface-spi = { git = "https://github.com/therealprof/display-interface", rev = "8fca041b0288740678f16c1d05cce21bd3867ee5" }
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "2744a5d" }
esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", rev = "2744a5d" }

```

**Comment by VersBinarii** [comment] 2024-07-28 10:28
I also can confirm that the support for Tricolor also works 😄

**Comment by avsaase** [comment] 2024-07-28 11:27
That's good to know. Thanks for letting me know. I'll make the first release today.
